Traceback (most recent call last):
  File "/g/data/xl04/ka6418/github/ausarg/nextflow/non-experimental/work/84/93d7b9749cbebb40fa11b0b5ea3aed/.command.sh", line 11, in <module>
    subprocess.run(['module unload python3'])
  File "/g/data/xl04/ka6418/miniconda/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/g/data/xl04/ka6418/miniconda/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/g/data/xl04/ka6418/miniconda/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'module unload python3'

======================================================================================
                  Resource Usage on 2023-11-21 10:01:10:
   Job Id:             101925397.gadi-pbs
   Project:            xl04
   Exit Status:        1
   Service Units:      0.04
   NCPUs Requested:    8                      NCPUs Used: 8               
                                           CPU Time Used: 00:00:02        
   Memory Requested:   16.0GB                Memory Used: 99.78MB         
   Walltime requested: 01:00:00            Walltime Used: 00:00:09        
   JobFS requested:    100.0MB                JobFS used: 0B              
======================================================================================
